name: Release Windows

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  localize:
    uses: ./.github/workflows/shared-steps.yml
    with:
      platform: windows
      version_command: |
        termius_version=$(choco search termius --exact | grep -Eo 'termius\s+([0-9]+\.[0-9]+\.[0-9]+)' | awk '{print $2}')
      install_command: choco install termius -y --no-progress
      source_path: $HOME/AppData/Local/Programs/Termius/resources/app.asar